enum PaletteGroup {
  CGA2Bit = 'IBM CGA 2-bit modes',
  RetroPC = 'Retro PCs',
  RetroVC = 'Retro Consoles',
  Mono = 'Monochrome',
  Duo = 'Dual Tone',
  RGB = 'RGB',
  CMYK = 'CMYK',
  Auto = 'Optimized (Auto)',
  Other = 'Other',
  Generated = 'AUTOGENERATED PALETTE',
  Hidden = 'HIDDEN PALETTE'
}

export default PaletteGroup;